const Data = {
  productItems: [
    {
      id: 1,
      discount: 40,
      cover: "./images/flash/flash-1.png",
      name: "Zapatillas Nike F3",
      price: 500,
    },
    {
      id: 2,
      discount: 10,
      cover: "./images/topper/topper2.png",
      name: "Riñonera ",
      price: 100,
    },
    {
      id: 3,
      discount: 25,
      cover: "./images/flash/flash-3.png",
      name: "Samsung Force",
      price: 900,
    },
    {
      id: 9,
      discount: 15,
      cover: "./images/nike/nike3.jfif",
      name: "Gorra Nike",
      price: 100,
    },
    {
      id: 4,
      discount: 5,
      cover: "./images/flash/flash-4.png",
      name: "Smart Watch Black",
      price: 350,
    },
    {
      id: 6,
      discount: 20,
      cover: "./images/topper/topper1.png",
      name: "Zapatillas Lacoste",
      price: 100,
    },
    {
      id: 7,
      discount: 30,
      cover: "./images/nike/nike.jfif",
      name: "Medias Nike",
      price: 100,
    },
    {
      id: 8,
      discount: 20,
      cover: "./images/electrodomesticos/electrodomestico.jfif",
      name: "Heladera",
      price: 2000,
    },
    {
      id: 9,
      discount: 20,
      cover: "./images/flash/flash-2.png",
      name: "Reloj Tommy Hilfiger Hendrix",
      price: 200,
    },
    {
      id: 10,
      discount: 15,
      cover: "./images/flash/remeranike.jfif",
      name: "Remera Nike",
      price: 100,
    },
  ],
};
export default Data;
